[application]
host = "127.0.0.1"
port = 8000

[database]
url = "postgres://stevegodin@localhost:5432/newsletter"

[email_client]
base_url = "localhost"
sender_email = "test@gmail.com"
authorization_token = "my-secret-token"
timeout_milliseconds = 10000